/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Card: typeof import('primevue/card')['default']
    DeviceList: typeof import('./src/devices/components/DeviceList.vue')['default']
    DeviceListItemRender: typeof import('./src/devices/components/DeviceListItem-Render.vue')['default']
    DeviceListItemValueAddressRender: typeof import('./src/devices/components/DeviceListItemValueAddress-Render.vue')['default']
    DeviceListItemValueRender: typeof import('./src/devices/components/DeviceListItemValue-Render.vue')['default']
    DeviceListItemValueStatusRender: typeof import('./src/devices/components/DeviceListItemValueStatus-Render.vue')['default']
    DeviceListItemValueTypeRender: typeof import('./src/devices/components/DeviceListItemValueType-Render.vue')['default']
    DeviceListItemValueUsageRender: typeof import('./src/devices/components/DeviceListItemValueUsage-Render.vue')['default']
    DeviceListRender: typeof import('./src/devices/components/DeviceList-Render.vue')['default']
    IconMdiAccountOnline: typeof import('~icons/mdi/account-online')['default']
    IconMdiAccountSupervisor: typeof import('~icons/mdi/account-supervisor')['default']
    IconMdiBitcoin: typeof import('~icons/mdi/bitcoin')['default']
    IconMdiCheckCircle: typeof import('~icons/mdi/check-circle')['default']
    IconMdiCloseCircle: typeof import('~icons/mdi/close-circle')['default']
    IconMdiComputer: typeof import('~icons/mdi/computer')['default']
    IconMdiGit: typeof import('~icons/mdi/git')['default']
    IconMdiLocalAreaNetwork: typeof import('~icons/mdi/local-area-network')['default']
    IconMdiNetworkPos: typeof import('~icons/mdi/network-pos')['default']
    IconMdiRaspberryPi: typeof import('~icons/mdi/raspberry-pi')['default']
    IconMdiWideAreaNetwork: typeof import('~icons/mdi/wide-area-network')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MeterGroup: typeof import('primevue/metergroup')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tag: typeof import('primevue/tag')['default']
    TheDevices: typeof import('./src/devices/views/TheDevices.vue')['default']
    TheHome: typeof import('./src/home/views/TheHome.vue')['default']
    TheNavbar: typeof import('./src/utils/components/TheNavbar.vue')['default']
  }
}
