/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    DeviceList: typeof import('./src/devices/components/DeviceList.vue')['default']
    DeviceListItem: typeof import('./src/devices/components/DeviceListItem.vue')['default']
    DeviceListItemActions: typeof import('./src/devices/components/DeviceListItemActions.vue')['default']
    DeviceListItemHeader: typeof import('./src/devices/components/DeviceListItemHeader.vue')['default']
    DeviceListItemValue: typeof import('./src/devices/components/DeviceListItemValue.vue')['default']
    DeviceListItemValueAddress: typeof import('./src/devices/components/DeviceListItemValueAddress.vue')['default']
    DeviceListItemValuePower: typeof import('./src/devices/components/DeviceListItemValuePower.vue')['default']
    DeviceListItemValueStatus: typeof import('./src/devices/components/DeviceListItemValueStatus.vue')['default']
    DeviceListItemValueType: typeof import('./src/devices/components/DeviceListItemValueType.vue')['default']
    DeviceListItemValueUsage: typeof import('./src/devices/components/DeviceListItemValueUsage.vue')['default']
    DeviceListItemValueVersion: typeof import('./src/devices/components/DeviceListItemValueVersion.vue')['default']
    IconMdiAccountOnline: typeof import('~icons/mdi/account-online')['default']
    IconMdiAccountSupervisor: typeof import('~icons/mdi/account-supervisor')['default']
    IconMdiBitcoin: typeof import('~icons/mdi/bitcoin')['default']
    IconMdiCheckCircle: typeof import('~icons/mdi/check-circle')['default']
    IconMdiCloseCircle: typeof import('~icons/mdi/close-circle')['default']
    IconMdiComputer: typeof import('~icons/mdi/computer')['default']
    IconMdiGit: typeof import('~icons/mdi/git')['default']
    IconMdiHamburgerMenu: typeof import('~icons/mdi/hamburger-menu')['default']
    IconMdiLocalAreaNetwork: typeof import('~icons/mdi/local-area-network')['default']
    IconMdiNetworkPos: typeof import('~icons/mdi/network-pos')['default']
    IconMdiRaspberryPi: typeof import('~icons/mdi/raspberry-pi')['default']
    IconMdiWideAreaNetwork: typeof import('~icons/mdi/wide-area-network')['default']
    InlineMessage: typeof import('primevue/inlinemessage')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    MeterGroup: typeof import('primevue/metergroup')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tag: typeof import('primevue/tag')['default']
    TheDevices: typeof import('./src/devices/views/TheDevices.vue')['default']
    TheHome: typeof import('./src/home/views/TheHome.vue')['default']
    TheNavbar: typeof import('./src/utils/components/TheNavbar.vue')['default']
  }
}
