/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Card: typeof import('primevue/card')['default']
    DeviceLabelAppVersionRender: typeof import('./src/devices/components/DeviceLabelAppVersion-Render.vue')['default']
    DeviceLabelHostOsVersionRender: typeof import('./src/devices/components/DeviceLabelHostOsVersion-Render.vue')['default']
    DeviceLabelIpRender: typeof import('./src/devices/components/DeviceLabelIp-Render.vue')['default']
    DeviceLabelStatusRender: typeof import('./src/devices/components/DeviceLabelStatus-Render.vue')['default']
    DeviceLabelSupervisorVersionRender: typeof import('./src/devices/components/DeviceLabelSupervisorVersion-Render.vue')['default']
    DeviceLabelTypeRender: typeof import('./src/devices/components/DeviceLabelType-Render.vue')['default']
    DeviceList: typeof import('./src/devices/components/DeviceList.vue')['default']
    DeviceListItemRender: typeof import('./src/devices/components/DeviceListItem-Render.vue')['default']
    DeviceListRender: typeof import('./src/devices/components/DeviceList-Render.vue')['default']
    IconMdiAccountOnline: typeof import('~icons/mdi/account-online')['default']
    IconMdiAccountSupervisor: typeof import('~icons/mdi/account-supervisor')['default']
    IconMdiBitcoin: typeof import('~icons/mdi/bitcoin')['default']
    IconMdiComputer: typeof import('~icons/mdi/computer')['default']
    IconMdiGit: typeof import('~icons/mdi/git')['default']
    IconMdiLocalAreaNetwork: typeof import('~icons/mdi/local-area-network')['default']
    IconMdiNetworkPos: typeof import('~icons/mdi/network-pos')['default']
    IconMdiWideAreaNetwork: typeof import('~icons/mdi/wide-area-network')['default']
    Menubar: typeof import('primevue/menubar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tag: typeof import('primevue/tag')['default']
    TheDevices: typeof import('./src/devices/views/TheDevices.vue')['default']
    TheHome: typeof import('./src/home/views/TheHome.vue')['default']
    TheNavbar: typeof import('./src/utils/components/TheNavbar.vue')['default']
  }
}
