---
name: ci
concurrency: deploy

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
    - main
    - develop

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Bicep deploy (what-if)
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.AZURE_RESOURCEGROUP }}
        template: MonitorNet.Infrastructure/main.bicep
        parameters: >-
          fncDevicesToken=${{ secrets.BALENA_TOKEN }}
          apimPublisherName=${{ secrets.APIM_PUBLISHER_NAME }}
          apimPublisherEmail=${{ secrets.APIM_PUBLISHER_EMAIL }}
        additionalArguments: --what-if

  backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Dotnet setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Dotnet restore
      run: dotnet restore

    - name: Dotnet build
      run: dotnet build

    - name: Dotnet test
      run: dotnet test

  frontend:
    runs-on: ubuntu-latest

    env:
      FRONTEND_DIRECTORY: MonitorNet.Frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Node setup
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Node install
      run: npm ci
      working-directory: ${{ env.FRONTEND_DIRECTORY }}

    - name: Node build
      run: npm run build
      working-directory: ${{ env.FRONTEND_DIRECTORY }}
