---
name: ci

# yamllint disable-line rule:truthy
on:
  push:
    branches:
    - main
    - develop

  pull_request:
    branches:
    - main
    - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Dotnet setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Dotnet restore
      run: dotnet restore

    - name: Dotnet build
      run: dotnet build

    - name: Dotnet test
      run: dotnet test
