---
name: deploy
concurrency: deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches:
    - main

jobs:
  infrastructure:
    runs-on: ubuntu-latest

    outputs:
      apim_name: ${{ steps.deploy.outputs.apim_name }}
      api_name: ${{ steps.deploy.outputs.api_name }}
      api_uri: ${{ steps.deploy.outputs.api_uri }}

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Bicep deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.AZURE_RESOURCEGROUP }}
        template: MonitorNet.Infrastructure/main.bicep
        parameters: >-
          fncDevicesToken=${{ secrets.BALENA_TOKEN }}
          apimPublisherName=${{ secrets.APIM_PUBLISHER_NAME }}
          apimPublisherEmail=${{ secrets.APIM_PUBLISHER_EMAIL }}
      id: deploy

  api:
    runs-on: ubuntu-latest
    needs: infrastructure

    env:
      FUNCTION_DIRECTORY: MonitorNet.Functions.Api

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Dotnet setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Dotnet restore
      run: dotnet restore
      working-directory: ${{ env.FUNCTION_DIRECTORY }}

    - name: Dotnet publish
      run: dotnet publish --output ./output
      working-directory: ${{ env.FUNCTION_DIRECTORY }}

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure deploy
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ needs.infrastructure.outputs.api_name }}
        package: ${{ env.FUNCTION_DIRECTORY }}/output

    - name: Azure apim import
      uses: azure/cli@v2
      with:
        inlineScript: >-
          az apim api import
          --api-id "api"
          --path "api"
          --resource-group "${{ vars.AZURE_RESOURCEGROUP }}"
          --service-name "${{ needs.infrastructure.outputs.apim_name }}"
          --specification-url "${{ needs.infrastructure.outputs.api_uri }}/api/openapi/1.0"
          --specification-format "OpenApiJson"
