---
name: deploy
concurrency: deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches:
    - main

jobs:
  infrastructure:
    runs-on: ubuntu-latest

    outputs:
      apim_name: ${{ steps.deploy.outputs.apim_name }}
      backend_app_name: ${{ steps.deploy.outputs.backend_app_name }}
      backend_app_uri: ${{ steps.deploy.outputs.backend_app_uri }}
      frontend_app_name: ${{ steps.deploy.outputs.frontend_app_name }}
      frontend_app_uri: ${{ steps.deploy.outputs.frontend_app_uri }}

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Bicep deploy
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.AZURE_RESOURCEGROUP }}
        template: MonitorNet.Infrastructure/main.bicep
        parameters: >-
          fncDevicesToken=${{ secrets.BALENA_TOKEN }}
          apimPublisherName=${{ secrets.APIM_PUBLISHER_NAME }}
          apimPublisherEmail=${{ secrets.APIM_PUBLISHER_EMAIL }}
      id: deploy

  backend:
    runs-on: ubuntu-latest
    needs: infrastructure

    env:
      BACKEND_DIRECTORY: MonitorNet.Functions.Api

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Dotnet setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Dotnet restore
      run: dotnet restore
      working-directory: ${{ env.BACKEND_DIRECTORY }}

    - name: Dotnet publish
      run: dotnet publish --output ./output
      working-directory: ${{ env.BACKEND_DIRECTORY }}

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure deploy
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ needs.infrastructure.outputs.backend_app_name }}
        package: ${{ env.BACKEND_DIRECTORY }}/output

    - name: Azure apim import
      uses: azure/cli@v2
      with:
        inlineScript: >-
          az apim api import
          --api-id "api"
          --path "api"
          --display-name "api"
          --description "Imported from: ${{ needs.infrastructure.outputs.backend_app_uri }}/api/openapi/1.0"
          --resource-group "${{ vars.AZURE_RESOURCEGROUP }}"
          --service-name "${{ needs.infrastructure.outputs.apim_name }}"
          --specification-url "${{ needs.infrastructure.outputs.backend_app_uri }}/api/openapi/1.0"
          --specification-format "OpenApiJson"

  frontend:
    runs-on: ubuntu-latest
    needs: infrastructure

    env:
      FRONTEND_DIRECTORY: MonitorNet.Frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Node setup
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Node install
      run: npm ci
      working-directory: ${{ env.FRONTEND_DIRECTORY }}

    - name: Node build
      run: npm run build
      working-directory: ${{ env.FRONTEND_DIRECTORY }}

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Static Web App Management Token
      uses: azure/cli@v2
      with:
        inlineScript: |-
          TOKEN=$(
            az staticwebapp secrets list \
            --name "swamonitornetprod001" \
            --query "properties.apiKey"
          )
          echo "value=$TOKEN" >> $GITHUB_ENV
      id: swa_token

    - name: Azure deploy
      uses: Azure/static-web-apps-deploy@c514ae36604047560e33605b78f71804967bfb7a
      with:
        azure_static_web_apps_api_token: ${{ steps.swa_token.outputs.value }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: upload
        app_location: ${{ env.FRONTEND_DIRECTORY }}
        output_location: ${{ env.FRONTEND_DIRECTORY }}/dist
